### ISSUE TITLE
newbie help

### ISSUE THREAD

**Issue by eastonrobotics-jeff** [pololu/pololu-usb-sdk#3]
I purchased a linear actuator and received the G2 item #1363 with it, and am trying to use it as a newbie.  Pulling the code from GitHub, following the instructions on the site.  Successfully cloned, opening in Visual Studio per instructions for G2 Windows and C#, but it fails to work.  Apparently, .NET is required, but current .NET flavor is 6.0 and the code appears to be written for 2.0?    errors attempting to debug per the instructions for smcG2 Example1 in Windows for C# gives three errors:
mscorlib.dll has a higher version 4.0.0.0 than found 2.0.0.0
smcG2\SmcG2\bin\Debug\SmcG2.dll not found
smcG2\SmcG2\bin\Debug\usbwrapper.dll not found

now what?

**Comment by DavidEGrayson** [comment]
You are using the code for the Simple Motor Controller G2, which is a different product than the Jrk G2.  This repository does not support the Jrk G2.  See the "Writing PC software to control the Jrk" section of the [Jrk G2 user's guide](https://www.pololu.com/docs/0J73).

**Comment by eastonrobotics-jeff** [comment]
Actually I *am* using the SMCG2.  The instructions for getting started are helpful but just barely.  I was able to launch the app GUI for Example1 but not using the instructions in the user guide.

**Comment by DavidEGrayson** [comment]
Oh, sorry for misreading your post.  I am glad you were able to resolve your issue.
